version: "3.9"

services:
  mongo:
    image: mongo:6.0
    container_name: order_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db

  app:
    build:
      context: .
      target: base
    container_name: order_app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      MONGO_DB: ${MONGO_DB}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOST: mongo
      MONGO_PORT: 27017
    volumes:
      - ./app:/app/app

  test:
    build:
      context: .
      target: dev
    container_name: order_test
    depends_on:
      - mongo
    environment:
      MONGO_DB: ${MONGO_DB}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOST: mongo
      MONGO_PORT: 27017
    volumes:
      - ./app:/app/app
    profiles: ["test"]

volumes:
  mongo_data:
